### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by RebeccaKorn** [hym0405/RNaseH_depletion#2]
Dear Dr. Huang,

When I try running the program 0.design_probe.py, I am running into an "IndexError: string index out of range" error as seen below:

(base) Rebeccas-MacBook-Pro:rRNA depletion rebeccakorn$ python 0.design_probe.py -i TIGR4_16S_rRNA -o rRNA_TIGR4
Traceback (most recent call last):
  File "0.design_probe.py", line 86, in <module>
    rRNA_pool = readFASTA(input_rRNA_PATH)
  File "0.design_probe.py", line 20, in readFASTA
    if each[0] == ">":
IndexError: string index out of range

I was wondering if you had any idea as to what this error could be referring to?

Best,
Rebecca

**Comment by hym0405** [comment]
Hi Rebecca,

The IndexError of "0.design_probe.py" could be caused by some empty lines in your FASTA files (maybe last line is empty?). You could try to delete empty lines in your FASTA files and run it again.

I hope this helps, but please let me know if you couldn't run it after deleting these lines and I will be happy to help you run it. (yh2989@cumc.columbia.edu)

Best,
Yiming

**Comment by RebeccaKorn** [comment]
Hi Yiming,

Thank you for all of your help, I was able to run the program.

Best,
Rebecca
